### ISSUE TITLE
Setup the project for development

### ISSUE THREAD

**Issue by BirukAbreham** [ironmussa/Bumblebee#129]
Hello guys I am trying to set up a development environment for customizing this project on a virtual VM of Ubuntu 20.04.

- When I try to run the project as in production mode it encounters a problem with initializing the Jupyter Kernel getaway 
- Used the command `bash bbi.sh start environment` on the root of the project

![issue](https://user-images.githubusercontent.com/24637978/124024231-9848f600-d9f7-11eb-85f0-ce68df11acad.png)

- The server environment is as follows
    - Ubuntu 20.04
    - MongoDB 4.4
    - conda 4.10.1 ( with `jupyter_kernel_gateway    2.4.3              pyh9f0ad1d_0    conda-forge`)
    - Node.js v12.22.1
- Any help will be appreciated.

**Comment by luis11011** [comment]
Hi Biruk,

you can terminate the shell script process and run `jupyter kernelgateway --JupyterWebsocketPersonality.list_kernels=True` or `jupyter kernelgateway --ip=0.0.0.0 --JupyterWebsocketPersonality.list_kernels=True --KernelGatewayApp.allow_origin='*'` while we fix this issue, since the node processes seems to start properly that should make it work by now.

I'll update this issue once it's solved.
